---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "ztp-spoke-01"
  namespace: "ztp-spoke-01"
spec:
  baseDomain: "ocp-poc-demo.local"
  pullSecretRef:
    name: "pull-secret"
  clusterImageSetNameRef: "openshift-v4.11.0"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDI0C7v3nrPyl6szdam99kd5DYTBq5/FP/YljGNnrCqGUdOZT2pIMppWTx9C/JgB2Qw/iVGYBT7sAOw1rbCP/47jJpx/QSmiIxPLhVcdeUMRwea7q7e+Gm94t7TJWKpb6X3clsz0K3bjtZ5Khy/FSn/xgZ1kNGp6oaKi7l4D629KQOI2Ke9b5j+lVEDD0dDPUZiYqa9JHIV0aviaNYRKxyAZ4cMLoDkih0+qvu2xzawvRj/IHtqJyFzIcg2pxy00uJiCOkbq+Wi/qBCfWIydt7auknE4ITAs1CTCVR6a9zLSjXlNXr287XxTlrodd/6w/rIJz8CUtKsjyn6JzIq1qMFNBbvpTVChsLRh5NoQ5FmFiodBkAW0DowRJSE7nWPvP2ffTGbI623rom5/mt46RPIVPrEL9EJPurHMrpN+xsFAyWrOh8lJ7+h2+iPkG8tTez903E5/JTn2cKdhRo9qIpm/630VsI/Rc7TB/cjhBhHQ7gWLCBA7KFuvuMv56QmxPc= ocpuser@bastion-local.ocp-poc-demo.com"
  clusters:
  - clusterName: "ztp-spoke-01"
    networkType: "OVNKubernetes"
    clusterLabels:
      common: true
      sites : "spoke1"
    clusterNetwork:
      - cidr: "10.128.0.0/14"
        hostPrefix: 23
    machineNetwork:
      - cidr: "192.168.100.0/24"
    serviceNetwork:
      - "172.30.0.0/16"
    nodes:
      - hostName: "ztp-spoke-01"
        role: "master"
        bmcAddress: redfish-virtualmedia+http://192.168.100.1:8000/redfish/v1/Systems/e2547246-c4a1-41d6-a2d7-758b4e667cdf"
        bmcCredentialsName:
          name: "bmc-secret"
        bootMACAddress: "52:54:00:20:99:f6"
        bootMode: "UEFI"
        rootDeviceHints:
          /dev/vda
        #  hctl: "0:0:0:0"
        #cpuset: "0-1,6-7"
        nodeNetwork:
          interfaces:
            - name: "enp1s0"
              macAddress: "52:54:00:20:99:f6"
          config:
            interfaces:
              - name: enp1s0
                type: ethernet
                state: up
                macAddress: "52:54:00:20:99:f6"
                ipv4:
                  enabled: true
                  address:
                    - ip: 192.168.100.5
                      prefix-length: 24
                  dhcp: false
                ipv6:
                  enabled: false
            dns-resolver:
              config:
                search:
                - ocp-poc-demo.local
                server:
                - 192.168.100.2
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-address: 192.168.100.1
                next-hop-interface: enp1s0
                table-id: 254
